name: OpenEUICC_for_Magisk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: set sercet
      run: |
        key_file_openeuicc_base=${{ secrets.KEY_FILE_OPENEUICC }}
        key_file_keystore_properties_half_base=${{ secrets.KEY_FILE_KEYSTORE_PROPERTIES_HALF }}
        echo "key_file_openeuicc_base=""$key_file_openeuicc_base" >> mysercetfile
        echo "key_file_keystore_properties_half_base=""$key_file_keystore_properties_half_base" >> mysercetfile
      
    - name: clone and build
      run: |
        chmod +x actions_build.sh
        ./actions_build.sh
        str_flag_change=`cat flag_change`
        if [ "$str_flag_change" = "1" ]; then echo "env_flag_change=1" >> $GITHUB_ENV; else echo "env_flag_change=0" >> $GITHUB_ENV; fi
    
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          output